# Generated by Django 5.2.6 on 2025-09-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='class_label',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
