# Generated by Django 5.2.6 on 2025-09-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_class_distribution_alter_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='histogram_1',
            field=models.ImageField(blank=True, null=True, upload_to='analysis/'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='histogram_2',
            field=models.ImageField(blank=True, null=True, upload_to='analysis/'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='metric_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='metric_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='overlay',
            field=models.ImageField(blank=True, null=True, upload_to='analysis/'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='result_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
