# Generated by Django 5.2.6 on 2025-09-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_analysisresult_histogram_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='global_stats',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
