# Generated by Django 5.2.6 on 2025-09-25 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_project_global_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisresult',
            name='histogram_2',
        ),
    ]
