# Generated by Django 5.2.6 on 2025-09-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_analysisresult_histogram_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='global_diam_hist',
            field=models.ImageField(blank=True, null=True, upload_to='global_stats/'),
        ),
        migrations.AddField(
            model_name='project',
            name='global_metrics2_hist',
            field=models.ImageField(blank=True, null=True, upload_to='global_stats/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='global_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
