# Generated by Django 5.2.6 on 2025-09-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_project_global_diam_hist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='diameters',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
