# Generated by Django 5.2.6 on 2025-09-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_analysisresult_diameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='class_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
