# Generated by Django 5.2.6 on 2025-09-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_sample_class_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='class_label',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
